name: CI Build and Test

on:
  workflow_call:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

concurrency:
  # Cancel in-progress runs on PR update
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Install dependencies
        run: go get ./...
        env:
          GOEXPERIMENT: jsonv2
      - name: Build
        run: go build -tags release -v ./...
        env:
          GOEXPERIMENT: jsonv2
      - name: Test
        run: make test
        shell: bash
        env:
          GOEXPERIMENT: jsonv2
      - name: Archive code coverage results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: code-coverage
          path: coverage.txt
      - name: Upload main coverage to Codecov
        id: code-cov-report
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          files: coverage.txt
          flags: main
          disable_search: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
