name: buf-push
on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  build:
    name: Check protos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: bufbuild/buf-action@85aebf73123b5c15fd5528aaecbf9129cddf7fa7 # v1.6.0
        with:
          format: false
          lint: true
          breaking: false
          push: true
          input: "api"
          token: ${{ secrets.BUF_TOKEN }}
